### PR TITLE
zt/ignore attributes

### PR DESCRIPTION
**Pull request by ztoolson**
Rails 4.2 ActiveModel now loads the models attributes directly from the schema which includes the columns that are ignored using `ignore_columns`. This removes the `ignored_columns` from the attributes.

### CODE REVIEW

**Comment by film42** [comment]
:+1: Would love to see this merged in soon.

**Comment by abrandoned** [comment]
bump? would be helpful ... thanks @ztoolson

**Comment by film42** [comment]
@nthj feel free to add some of us as contributors to the repo if you don't have time to look through PRs right now.

**Comment by ztoolson** [comment]
I accidentally closed this. The pull request is still valid!

**Comment by grosser** [comment]
@nthj merge ?

**Comment by nthj** [comment]
Merged, will see about shipping a new version soon!

**Comment by grosser** [comment]
:heart:

**Comment by tlrdstd** [comment]
Would it be possible to cut a new version now that this pull request has been merged? I have it locally monkeypatched, and I'd love to just use the official code!

**Comment by mnoack** [comment]
@nthj :+1: to cut a release. We've just upgrading to Rails 4.2 (hopefully only for a little while until we move to 5.0/5.1) but it would be great not to point to the master branch.

**Comment by seanchambo** [comment]
Would be great if you could cut a release @nthj! We are also upgrading to rails 4.2 and would love to not have to point to master.

**Comment by nthj** [comment]
`v0.4.0` pushed, thanks all. Let me know if any issues.

**Comment by nthj** [comment]
I've also added @mnoack as an owner, as I'm not actively using `ignorable` anymore. Probably best that someone with skin in the game has access!

**Pull request merged**
